const sagaActionIds = {
  SET_COURSES: 'SET_COURSES',
  SERVER_REQUEST: 'SERVER_REQUEST',
  SET_DATA_FROM_SERVER: 'SET_DATA_FROM_SERVER',
  DELETE_SERVER_ITEM: 'DELETE_SERVER_ITEM',
  EDIT_SERVER_ITEM: 'EDIT_SERVER_ITEM',
  ADD_SERVER_ITEM: 'ADD_SERVER_ITEM',
  UPDATE_SERVER_ITEM: 'UPDATE_SERVER_ITEM',
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
};

export default sagaActionIds;
